### ISSUE TITLE
注释删除后Comments窗口记录还在

### ISSUE THREAD

**Issue by zhuzhu-Top** [JayRE114514/UserComment#2]
如标题所示，这个算是bug吗
![image](https://github.com/JayRE114514/UserComment/assets/35734511/5c6a182e-0a2b-4b62-801a-2fd7e2a95667)

**Comment by JayRE114514** [comment]
感谢反馈, 我后续更新会修复它。

zhuzhu ***@***.***> 于2023年6月18日周日 13:45写道：

**Comment by zhuzhu-Top** [comment]
感谢
